# Generated by Django 4.0 on 2022-07-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CartBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_quantity', models.IntegerField(default=0)),
                ('book_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('book_purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book')),
                ('book_type_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.booktypeprice')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
