# Generated by Django 4.0 on 2022-07-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('shipment_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('shipment_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('free_shipment_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
