# name: Test Project
# on: push
# jobs:
#      test:
#           runs-on: macos-latest
#           steps:
#                - name: Get code
#                     uses: actions/checkout@v3 
name: Build and Deploy

on:
     push:
          branches: [ main ]

jobs:
     build_and_test:
          runs-on: macos-latest
          steps:
               - name: Checkout code
                    uses: actions/checkout@v3
               - name: Setup Python
                    uses: actions/setup-python@v4
                    with:
                         python-version: '3.10'
               - name: Install dependencies
                    run:
                         python -m pip install --upgrade pip
                         pip install -r requirements.txt
               - name: Run tests
                    run: python manage.py test
     deploy:
          runs-on: macos-latest
          needs: [ build_and_test ]
          steps:
               - name: echo Hello World
                    run: echo "Hello World"


